version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  linter:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
            - run: sudo npm install -g wait-on
            - run: bin/start_and_test
workflows:
    linter:
      jobs:
        - linter